[theme]
# Force dark theme for the entire app
base = "dark"
primaryColor = "#198A00"  # Zambian green
backgroundColor = "#0A0A0A"  # Dark background
secondaryBackgroundColor = "#1A1A1A"  # Slightly lighter dark
textColor = "#F3F4F6"  # Light text for readability
font = "sans serif"

[client]
# Disable theme change button - users cannot switch themes
showSidebarNavigation = true
toolbarMode = "minimal"

[browser]
# Additional browser settings
gatherUsageStats = false