[theme]
primaryColor = "#198A00"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f8f0"
textColor = "#262730"

[client]
displayEnabled = false
toolbarMode = "minimal"
showErrorDetails = false

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
runOnSave = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[logger]
level = "error"