[theme]
primaryColor = "#198A00"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f8f0"
textColor = "#262730"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false